[widget] don't open soft keyboard if editor is readonly
gioui/gio pull request #122
Opened 2023-09-04 13:43 UTC by g45t345rt

For mobile, you don't need the keyboard for editing if it's readonly.

2023-09-18 15:33 UTC, eliasnaur requested changes
Thank you. One comment about `Editor.requestFocus`. Please sign-off and prefix your commit messages according to the [constribution guidelines](https://gioui.org/doc/contribute). For example:

`widget: don't let readonly Editors ask for focus and keyboard`

2023-09-18 15:33 UTC, eliasnaur commented on widget/editor.go
>  	if e.requestFocus {
Wouldn't it be better if `e.requestFocus` is not set when `e.ReadOnly`? Then read-only Editors will never reach this branch, and not ask for focus with the `key.FocusOp` below.

2024-01-09 15:15 UTC, eliasnaur commented
I believe this PR is obsoleted by https://todo.sr.ht/~eliasnaur/gio/550.

2024-01-09 15:30 UTC, g45t345rt commented
Dope. I'll take a look at this branch, and I really the approach you're taking with the new releases.

2024-01-09 15:30 UTC, closed without merging