cmd/gogio: fix icon/resources for Android
gioui/gio pull request #15
Opened 2021-02-21 16:52 UTC by Inkeliz

Previously that patch, gogio unzip the `link.apk` (generated by AAPT2) to an temporary folder and then compress it again to a new `app.ap_` file.

For some unknown reason, that unzip-then-zip doesn't work. The resources are included but is corrupted in somehow. That PR aims to fix that by avoid the extraction to an temporary folder.

2021-02-21 18:04 UTC, eliasnaur commented on cmd/gogio/androidbuild.go
> +		h := f.FileHeader
I think

```
h := zip.FileHeader{
    Name: f.Name,
    // Other required fields?
    ...
}
```

is safer than re-using and clearing fields from the original.

2021-02-21 18:05 UTC, eliasnaur requested changes
I'd love to know what corrupts the resources, but the change looks good in any case.

2021-02-21 18:05 UTC, eliasnaur commented on cmd/gogio/androidbuild.go
>  	// files. Unpack the apk from aapt2 and re-zip its contents along with
Update comment to match your new implementation.

2021-02-21 18:05 UTC, eliasnaur commented on cmd/gogio/androidbuild.go
> +	// Append new files (that doesn't exists inside the link.apk):
Nit: End comment sentences with a period, not colons. Here and below.

2021-02-21 19:40 UTC, Inkeliz commented
I don't know what is the cause. Maybe it could be because Windows uses `\` as path, and that path is provide as "name" or some compression is wrong?! 

-----

That is what the Android Studio sees before:
![gio-res-old](https://user-images.githubusercontent.com/4644332/108636270-2aeeec80-747c-11eb-9ae7-1f360495db85.PNG)

It's how it's detecting now:
![gio-res-new](https://user-images.githubusercontent.com/4644332/108636309-4d810580-747c-11eb-876f-b17e39e28ee0.PNG)

Since the "res" folder doesn't appears on Android Studio (on the previous version), I tried to "rewrite" the zip/unzip stuff and works. But, the root-cause is unknown. 😜

2021-02-22 11:11 UTC, eliasnaur commented
Thanks, merged.

2021-02-22 11:11 UTC, closed without merging